name: RSpec Test

on: [push, pull_request]

# Enables a "Run workflow" button on the Actions tab
# workflow_dispatch:

jobs:
  test-app:
    matrix:
      os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
          ruby-version: 2.7.5

      - name: Run tests
        run: |
          rspec
